// Auto-generated by cove (do not edit)
// Installs the app-bound agent registry seam (registerAgentRegistry) so getRegisteredAgent(name)
// resolves a declared CreatedAgent at runtime. Side-effect import this from convex/http.ts. Pure.

import { registerAgentRegistry, registry } from "../agentRegistry.ts";

registerAgentRegistry(registry);

export { getRegisteredAgent, listRegisteredAgents } from "../agentRegistry.ts";
