// Auto-generated by cove (do not edit)
// Installs the app-bound workflow registry seam (registerWorkflowRegistry) so getRegisteredWorkflow(name)
// resolves a declared workflow handler at runtime. Side-effect import this from convex/http.ts. Pure.

import { registerWorkflowRegistry, workflows } from "../workflowRegistry.ts";

registerWorkflowRegistry(workflows);

export { getRegisteredWorkflow } from "../workflowRegistry.ts";
