// G2.4 CLI test — codegen emits byte-stable output; a second run with the same input is identical (idempotency);
// the patched http.ts replaces the workflow 404 stub + installs the resolver imports; no brand leakage.
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { generateAgentResolver, renderAgentResolver } from "../codegen/generate-agent-registry.ts";
import {
	ensureResolverImports,
	generateHttpEntry,
	patchWorkflowRoute,
} from "../codegen/generate-http-entry.ts";
import {
	generateWorkflowResolver,
	renderWorkflowResolver,
} from "../codegen/generate-workflow-registry.ts";

let dir: string;
beforeEach(() => {
	dir = fs.mkdtempSync(path.join(os.tmpdir(), "cove-codegen-"));
});
afterEach(() => {
	fs.rmSync(dir, { recursive: true, force: true });
});

const NO_LEAK = /flue|__flueCreatedAgent|\[flue\]|type:\s*['"]skill['"]/;

describe("agent/workflow resolver codegen", () => {
	it("renders a byte-stable agentResolver carrying the Auto-generated banner", () => {
		const a = renderAgentResolver("registry");
		const b = renderAgentResolver("registry");
		expect(a).toBe(b);
		expect(a.split("\n")[0]).toBe("// Auto-generated by cove (do not edit)");
		expect(a).toContain('import { registerAgentRegistry, registry } from "../agentRegistry.ts";');
		expect(a).toContain("registerAgentRegistry(registry);");
		expect(a).toContain('export { getRegisteredAgent, listRegisteredAgents } from "../agentRegistry.ts";');
		expect(a).not.toMatch(NO_LEAK);
		expect(a).not.toContain('"use node"');
	});

	it("renders a byte-stable workflowResolver (separate from the agent resolver, D18)", () => {
		const a = renderWorkflowResolver("workflows");
		expect(a).toBe(renderWorkflowResolver("workflows"));
		expect(a.split("\n")[0]).toBe("// Auto-generated by cove (do not edit)");
		expect(a).toContain('import { registerWorkflowRegistry, workflows } from "../workflowRegistry.ts";');
		expect(a).toContain('export { getRegisteredWorkflow } from "../workflowRegistry.ts";');
		expect(a).not.toContain("getRegisteredAgent"); // workflows stay out of the agent resolver.
		expect(a).not.toMatch(NO_LEAK);
	});

	it("is idempotent: writes on first run, no-op on a second run with identical input", () => {
		const convexDir = path.join(dir, "convex");
		fs.mkdirSync(convexDir, { recursive: true });

		const first = generateAgentResolver({ convexDir, exportName: "registry" });
		expect(first.changed).toBe(true);
		const bytes1 = fs.readFileSync(first.path, "utf-8");

		const second = generateAgentResolver({ convexDir, exportName: "registry" });
		expect(second.changed).toBe(false); // content-compare → 0 files written.
		expect(fs.readFileSync(second.path, "utf-8")).toBe(bytes1);

		const wf = generateWorkflowResolver({ convexDir, exportName: "workflows" });
		expect(wf.changed).toBe(true);
		expect(generateWorkflowResolver({ convexDir, exportName: "workflows" }).changed).toBe(false);
	});
});

// A representative pre-patch http.ts (the P8 stub shape), reduced to the surface the patch touches.
const STUB_HTTP = `// reference header line 1
// reference header line 2
import { httpRouter } from "convex/server";
import { api } from "./_generated/api";
import { httpAction } from "./_generated/server";
import { InvalidRequestError, renderHttpError, WorkflowNotFoundError } from "../src/runtime/http.ts";
import { runAuthorize } from "./auth.ts";

const http = httpRouter();

function pathSegments(req) { return new URL(req.url).pathname.split("/").filter(Boolean); }

// POST /workflows/:name — 404 stub.
http.route({
	pathPrefix: "/workflows/",
	method: "POST",
	handler: httpAction(async (_ctx, req) => {
		const name = pathSegments(req)[1] ?? "";
		const { status, body } = renderHttpError(new WorkflowNotFoundError(name));
		return Response.json(body, { status });
	}),
});

export default http;
`;

describe("http entry codegen", () => {
	it("prepends both resolver imports (after the reference-header comments)", () => {
		const patched = ensureResolverImports(STUB_HTTP);
		expect(patched).toContain('import "./_cove/agentResolver.ts";');
		// The workflow import is present until promoted to a named import by the route patch.
		expect(patched).toContain("_cove/workflowResolver.ts");
		// Inserted after the leading // header lines, before the first real import.
		const lines = patched.split("\n");
		const agentLine = lines.findIndex((l) => l.includes("agentResolver.ts"));
		expect(lines[agentLine - 1]?.trim().startsWith("//")).toBe(true);
		expect(ensureResolverImports(patched)).toBe(patched); // idempotent.
	});

	it("replaces the /workflows 404 stub with a getRegisteredWorkflow lookup + submitWorkflow", () => {
		const patched = patchWorkflowRoute(STUB_HTTP);
		expect(patched).toContain("getRegisteredWorkflow(name)");
		expect(patched).toContain("api.invoke.submit.submitWorkflow");
		expect(patched).toContain('throw new WorkflowNotFoundError(name)'); // unknown still 404s.
		expect(patched).not.toContain("renderHttpError(new WorkflowNotFoundError(name))"); // the stub body is gone.
		expect(patched).toContain("// cove:workflow-route (auto-generated)");
		expect(patchWorkflowRoute(patched)).toBe(patched); // idempotent (marker guard).
	});

	it("generateHttpEntry patches a real file idempotently + emits no brand leakage / no use node", () => {
		const convexDir = path.join(dir, "convex");
		fs.mkdirSync(convexDir, { recursive: true });
		fs.writeFileSync(path.join(convexDir, "http.ts"), STUB_HTTP, "utf-8");

		const first = generateHttpEntry({ convexDir });
		expect(first.mode).toBe("patched");
		expect(first.changed).toBe(true);
		const bytes = fs.readFileSync(first.path, "utf-8");
		expect(bytes).toContain("getRegisteredWorkflow");
		expect(bytes).not.toContain('"use node"');
		expect(bytes).not.toMatch(NO_LEAK);

		const second = generateHttpEntry({ convexDir });
		expect(second.changed).toBe(false); // no-op rebuild writes 0 files.
		expect(fs.readFileSync(second.path, "utf-8")).toBe(bytes);
	});

	it("validate-don't-overwrite when http.ts is marked // cove:user-authored", () => {
		const convexDir = path.join(dir, "convex");
		fs.mkdirSync(convexDir, { recursive: true });
		const authored = `// cove:user-authored\n${STUB_HTTP}`;
		fs.writeFileSync(path.join(convexDir, "http.ts"), authored, "utf-8");

		const result = generateHttpEntry({ convexDir });
		expect(result.mode).toBe("validated");
		const bytes = fs.readFileSync(result.path, "utf-8");
		// The user's 404 stub route is NOT rewritten...
		expect(bytes).toContain("renderHttpError(new WorkflowNotFoundError(name))");
		expect(bytes).not.toContain("// cove:workflow-route (auto-generated)");
		// ...but the resolver imports ARE ensured (so the seams still install).
		expect(bytes).toContain('import "./_cove/agentResolver.ts";');
	});

	it("validate-don't-overwrite when convex/app.ts exists", () => {
		const convexDir = path.join(dir, "convex");
		fs.mkdirSync(convexDir, { recursive: true });
		fs.writeFileSync(path.join(convexDir, "http.ts"), STUB_HTTP, "utf-8");
		fs.writeFileSync(path.join(convexDir, "app.ts"), "export default {};\n", "utf-8");

		const result = generateHttpEntry({ convexDir });
		expect(result.mode).toBe("validated");
	});
});
