// New (Convex backend) · @cove/cli — extension resolver codegen (pragmatic-refactor Phase 5).
// Sibling of generate-tool-registry.ts: import the user's extension registry → emit a sidecar that installs
// registerExtensionRegistry + re-exports getRegisteredExtension. setup.ts resolves an agent's named
// extensions by NAME from this registry (closures recovered by re-running the registration-only factory).
// By convention the registry is the `extensions` export of convex/extensionRegistry.ts; `cove init` scaffolds
// it. The emitted file is PURE (no "use node"). BYTE-STABLE: a fixed template, content-compared before write.

import * as path from "node:path";
import { writeIfChanged } from "./write-if-changed.ts";

export const EXTENSION_RESOLVER_BANNER = "// Auto-generated by cove (do not edit)";

export interface GenerateExtensionResolverOptions {
	/** Absolute Convex app dir (where extensionRegistry.ts lives + _cove/ is emitted). */
	convexDir: string;
	/** Export name the registry is bound to in extensionRegistry.ts (default "extensions"). */
	exportName: string;
}

/** Render the extensionResolver.ts source (deterministic). */
export function renderExtensionResolver(exportName: string): string {
	return [
		EXTENSION_RESOLVER_BANNER,
		"// Installs the app-bound extension registry seam (registerExtensionRegistry) so getRegisteredExtension(name)",
		"// resolves a declared extension factory at runtime. Side-effect import this from setup.ts. Pure.",
		"",
		`import { registerExtensionRegistry, ${exportName} } from "../extensionRegistry.ts";`,
		"",
		`registerExtensionRegistry(${exportName});`,
		"",
		`export { getRegisteredExtension, listRegisteredExtensions } from "../extensionRegistry.ts";`,
		"",
	].join("\n");
}

/** Emit `convex/_cove/extensionResolver.ts`. Returns whether the file changed. */
export function generateExtensionResolver(
	opts: GenerateExtensionResolverOptions,
): { path: string; changed: boolean } {
	const filePath = path.join(opts.convexDir, "_cove", "extensionResolver.ts");
	const source = renderExtensionResolver(opts.exportName);
	const changed = writeIfChanged(filePath, source);
	return { path: filePath, changed };
}
