// New (Convex backend) · @cove/cli — agent resolver codegen.
// Codegen analogue of flue · @flue/cli · packages/cli/src/lib/build-plugin-node.ts `generateEntryPoint`
// (lines 14–441). The Hono/serve()/coordinator/sqlite/IPC emitted template is DROPPED WHOLESALE — Convex
// owns the server. Kept ONLY the pattern: import the user's registry → emit a sidecar that *installs* the
// orphaned seam (registerAgentRegistry) + re-exports the by-name lookup.
//
// DECISION (stated in-file): emit a SIDECAR (`convex/_cove/agentResolver.ts`) rather than rewriting the
// hand-authored `agentRegistry.ts` in place — the authoring file stays user-owned. The sidecar's
// side-effect import (registerAgentRegistry at module top) is what `convex/http.ts` imports so the seam
// installs at module load. The emitted file is PURE: no "use node", no box, no LLM (doc 08 §3).
//
// BYTE-STABLE: the body is a fixed template (no per-name interpolation needed — the registry object is
// imported wholesale), so two runs over the same input produce identical bytes. Content-compared before
// write by the caller (build.ts / generate-http-entry.ts share writeIfChanged).

import * as path from "node:path";
import { writeIfChanged } from "./write-if-changed.ts";

export const AGENT_RESOLVER_BANNER = "// Auto-generated by cove (do not edit)";

export interface GenerateAgentResolverOptions {
	/** Absolute Convex app dir (where agentRegistry.ts lives + _cove/ is emitted). */
	convexDir: string;
	/** Export name the registry is bound to in agentRegistry.ts (default "registry"). */
	exportName: string;
}

/** Render the agentResolver.ts source (deterministic). */
export function renderAgentResolver(exportName: string): string {
	return [
		AGENT_RESOLVER_BANNER,
		"// Installs the app-bound agent registry seam (registerAgentRegistry) so getRegisteredAgent(name)",
		"// resolves a declared CreatedAgent at runtime. Side-effect import this from convex/http.ts. Pure.",
		"",
		`import { registerAgentRegistry, ${exportName} } from "../agentRegistry.ts";`,
		"",
		`registerAgentRegistry(${exportName});`,
		"",
		`export { getRegisteredAgent, listRegisteredAgents } from "../agentRegistry.ts";`,
		"",
	].join("\n");
}

/** Emit `convex/_cove/agentResolver.ts`. Returns whether the file changed. */
export function generateAgentResolver(opts: GenerateAgentResolverOptions): { path: string; changed: boolean } {
	const filePath = path.join(opts.convexDir, "_cove", "agentResolver.ts");
	const source = renderAgentResolver(opts.exportName);
	const changed = writeIfChanged(filePath, source);
	return { path: filePath, changed };
}
