// New (Convex backend) · @cove/cli — workflow resolver codegen.
// Sibling of generate-agent-registry.ts (same pattern: import the user's registry → emit a sidecar that
// installs registerWorkflowRegistry + re-exports getRegisteredWorkflow). Codegen analogue of flue ·
// @flue/cli · build-plugin-node.ts `generateEntryPoint` (Hono/serve template DROPPED wholesale).
//
// Workflows are kept OUT of the agent resolver (D18): a workflow run is a distinct `kind:"workflow"` run,
// never folded into the agent registry/resolver (that would re-introduce the agentName-rekey conflation).
// The emitted file is PURE: no "use node", no box, no LLM.
//
// BYTE-STABLE: a fixed template, content-compared before write.

import * as path from "node:path";
import { writeIfChanged } from "./write-if-changed.ts";

export const WORKFLOW_RESOLVER_BANNER = "// Auto-generated by cove (do not edit)";

export interface GenerateWorkflowResolverOptions {
	/** Absolute Convex app dir (where workflowRegistry.ts lives + _cove/ is emitted). */
	convexDir: string;
	/** Export name the registry is bound to in workflowRegistry.ts (default "workflows"). */
	exportName: string;
}

/** Render the workflowResolver.ts source (deterministic). */
export function renderWorkflowResolver(exportName: string): string {
	return [
		WORKFLOW_RESOLVER_BANNER,
		"// Installs the app-bound workflow registry seam (registerWorkflowRegistry) so getRegisteredWorkflow(name)",
		"// resolves a declared workflow handler at runtime. Side-effect import this from convex/http.ts. Pure.",
		"",
		`import { registerWorkflowRegistry, ${exportName} } from "../workflowRegistry.ts";`,
		"",
		`registerWorkflowRegistry(${exportName});`,
		"",
		`export { getRegisteredWorkflow } from "../workflowRegistry.ts";`,
		"",
	].join("\n");
}

/** Emit `convex/_cove/workflowResolver.ts`. Returns whether the file changed. */
export function generateWorkflowResolver(
	opts: GenerateWorkflowResolverOptions,
): { path: string; changed: boolean } {
	const filePath = path.join(opts.convexDir, "_cove", "workflowResolver.ts");
	const source = renderWorkflowResolver(opts.exportName);
	const changed = writeIfChanged(filePath, source);
	return { path: filePath, changed };
}
