// New (Convex backend) · @cove/cli — tool resolver codegen (pragmatic-refactor Phase 3b).
// Sibling of generate-agent-registry.ts / generate-workflow-registry.ts: import the user's tool registry →
// emit a sidecar that installs registerToolRegistry + re-exports getRegisteredTool. The durable engine
// (setup freeze + dispatchTools recovery) reads the registry by NAME to recover each user tool's `execute`
// closure per isolate (the closure can't cross the workflow journal). The emitted file is PURE (no "use
// node"). By convention the registry is the `tools` export (like `workflows`); `cove init` scaffolds it.
//
// BYTE-STABLE: a fixed template, content-compared before write.

import * as path from "node:path";
import { writeIfChanged } from "./write-if-changed.ts";

export const TOOL_RESOLVER_BANNER = "// Auto-generated by cove (do not edit)";

export interface GenerateToolResolverOptions {
	/** Absolute Convex app dir (where toolRegistry.ts lives + _cove/ is emitted). */
	convexDir: string;
	/** Export name the registry is bound to in toolRegistry.ts (default "tools"). */
	exportName: string;
}

/** Render the toolResolver.ts source (deterministic). */
export function renderToolResolver(exportName: string): string {
	return [
		TOOL_RESOLVER_BANNER,
		"// Installs the app-bound tool registry seam (registerToolRegistry) so getRegisteredTool(name) recovers",
		"// a declared tool's execute closure at runtime. Side-effect import this from setup.ts/dispatchTools.ts. Pure.",
		"",
		`import { registerToolRegistry, ${exportName} } from "../toolRegistry.ts";`,
		"",
		`registerToolRegistry(${exportName});`,
		"",
		`export { getRegisteredTool, listRegisteredTools } from "../toolRegistry.ts";`,
		"",
	].join("\n");
}

/** Emit `convex/_cove/toolResolver.ts`. Returns whether the file changed. */
export function generateToolResolver(opts: GenerateToolResolverOptions): { path: string; changed: boolean } {
	const filePath = path.join(opts.convexDir, "_cove", "toolResolver.ts");
	const source = renderToolResolver(opts.exportName);
	const changed = writeIfChanged(filePath, source);
	return { path: filePath, changed };
}
